//Redux types for items

export const GET_MEETING_ITEMS_REQUEST = "GET_MEETING_ITEMS_REQUEST";
export const GET_MEETING_ITEMS_SUCCESS = "GET_MEETING_ITEMS_SUCCESS";
export const GET_MEETING_ITEMS_FAILURE = "GET_MEETING_ITEMS_FAILURE";
