export const STORE_USER = "STORE_USER";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CREATE_ACCOUNT_REQUEST = "CREATE_ACCOUNT_REQUEST";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";
export const SET_USER_INFO = "SET_USER_INFO";
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_MEETING_PARTICIPANTS_REQUEST =
  "GET_MEETING_PARTICIPANTS_REQUEST";
export const GET_MEETING_PARTICIPANTS_SUCCESS =
  "GET_MEETING_PARTICIPANTS_SUCCESS";
export const GET_MEETING_PARTICIPANTS_FAILURE =
  "GET_MEETING_PARTICIPANTS_FAILURE";
